### ISSUE TITLE
/tp don't work + lot of red lines in console (Devision by zero, InvalidCastException, etc.)

### ISSUE THREAD

**Issue by art1fact** [RocketFoundation/Rocket#456] opened 2015-07-18 13:32 UTC
tp Log:
[7/18/2015 4:29:27 PM] [Error] An error occured while executing command /tp mont: System.TypeLoadException: Could not load type 'SDG.Unturned.NodeLocation' from assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
  at Rocket.Unturned.Commands.RocketCommandBase.execute (CSteamID caller, System.String command) [0x00000] in <filename unknown>:0 

Other red lines:
[7/18/2015 3:11:44 PM] [Error] InvalidCastException: Cannot cast from source type to destination type. - SDG.Unturned.PlayerDamageMultiplier.armor (ELimb limb, SDG.Unturned.Player player)
SDG.Unturned.DamageTool.damage (SDG.Unturned.Player player, EDeathCause cause, ELimb limb, CSteamID killer, Vector3 direction, SDG.Unturned.PlayerDamageMultiplier multiplier, Single times, Boolean armor, SDG.Unturned.EPlayerKill& kill)
SDG.Unturned.UseableGun.fire ()
SDG.Unturned.UseableGun.tock (UInt32 clock)
SDG.Unturned.PlayerEquipment.tock (UInt32 clock)
SDG.Unturned.PlayerInput.askInputPlayer (CSteamID steamID, System.Boolean[] k, Vector3 point, Single lx, Single ly)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Steam.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Steam.listenServer (Int32 channel)
SDG.Unturned.Steam.listen ()
SDG.Unturned.Steam.Update ()

And

[7/18/2015 3:00:04 PM] [Exception] Rocket.Unturned >> Exception in UnloadPlugin: System.NullReferenceException: 
  at (wrapper managed-to-native) UnityEngine.Component:get_gameObject ()
  at Rocket.Unturned.Plugins.PluginManager+<RemoveRocketPlayerComponents>c__AnonStorey1.<>m__1 (SDG.Unturned.SteamPlayer p) [0x00000] in <filename unknown>:0 
  at System.Collections.Generic.List`1[SDG.Unturned.SteamPlayer].ForEach (System.Action`1 action) [0x00000] in <filename unknown>:0 
  at Rocket.Unturned.Plugins.PluginManager.RemoveRocketPlayerComponents (System.Reflection.Assembly plugin) [0x00000] in <filename unknown>:0 

And

[7/18/2015 4:39:07 PM] [Error] DivideByZeroException: Division by zero - SDG.Unturned.LightingManager.updateLighting ()
SDG.Unturned.LightingManager.tellLighting (CSteamID steamID, UInt32 serverTime, UInt32 newCycle, UInt32 newOffset, Byte moon)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.SteamChannel.send (ESteamCall mode, ESteamPacket type, Int32 size, System.Byte[] packet)
SDG.Unturned.SteamChannel.send (System.String name, ESteamCall mode, ESteamPacket type, System.Object[] arguments)
SDG.Unturned.VehicleManager.askVehicleHeadlights (CSteamID steamID)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Steam.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Steam.listenServer (Int32 channel)
SDG.Unturned.Steam.listen ()
SDG.Unturned.Steam.Update ()

**Comment by Trojaner25** [comment] 2015-07-18 13:57
The last exception seems to be caused by Unturned, not Rocket.

**Comment by art1fact** [comment] 2015-07-18 14:03
@Trojaner25, just notice.

**Comment by jakeob22** [comment] 2015-07-18 16:57
I'm having this same problem, let me know if you find a solution.

**Comment by art1fact** [comment] 2015-07-18 17:02
@jakeob22 I think this issues has only two solution - rocket patch and unturned patch

**Comment by jakeob22** [comment] 2015-07-18 17:08
@art1fact I'm thinking the same thing. I guess we'll just need to wait it out.

**Comment by art1fact** [comment] 2015-07-18 17:12
@jakeob22 3 days of unstable things. Omg.

**Comment by fr34kyn01535** [comment] 2015-07-18 18:06
The first exception is not complete & just fixed anyway. Since this is not a proper bug report i will close it now, most of the issues are unturned issues tho.

**Closed by fr34kyn01535** 2015-07-18 18:06 UTC
