### ISSUE TITLE
Memory leak causes server crash

### ISSUE THREAD

**Issue by pardisproud** [RocketFoundation/Rocket#220] opened 2015-07-04 19:00 UTC
I reported this here once and you guys said it was the game but when i reported it to the Unturned github they told me this, please look, they said it was a memory leak.
https://github.com/SmartlyDressedGames/Unturned/issues/9#issuecomment-118538732

**Comment by fr34kyn01535** [comment] 2015-07-04 19:51
I was able to look at it on his machine & couldn't right away replicate. It is possible to replicate this with vanilla tho. Let somebody connect & then close your firewall

**Comment by pardisproud** [comment] 2015-07-04 20:01
I fixed it, I reinstalled everything fresh start but just copied some of the text from the plugin config files, works fine

**Comment by pardisproud** [comment] 2015-07-04 20:04
nevermind just took longer

**Comment by pardisproud** [comment] 2015-07-04 20:05
and what about replicating, what do i do?

**Comment by pardisproud** [comment] 2015-07-05 06:38
any solutions yet?

**Comment by fr34kyn01535** [comment] 2015-07-05 06:42
Read, plspls

**Comment by pardisproud** [comment] 2015-07-05 06:55
what do you mean by let someone connect and close my firewall? to my sonic wall or my pc?

**Comment by pardisproud** [comment] 2015-07-05 07:55
So this is  what happens in my eyes, from fresh install and update, to crash report.
https://www.youtube.com/watch?v=96DFdJuLrck

**Comment by kaegann** [comment] 2015-07-05 20:49
Figures they didn't give you an actual answer lol. Seems to be their thing on this big tracker. Present them with a bug and they just say it can't be replicated then give you some bs on how not to fix it.

**Comment by fr34kyn01535** [comment] 2015-07-05 20:59
This bug is not fixed, kaegann shut the bullshit and cry somewhere else.
Mash could reproduce on his windows server, but i could not reproduce it on my servers or my own machine.
On Mashes machine tho was it also possible to reproduce it with vanilla Unturned by joining the machine once and then leaving, triggering the same memory leak - which lead me thinking it is a unturned bug. Since i was not able to replicate there is no progress, unless you want to send me your machine or figure a way to replicate on other machines then there is nothing we can do without nelson profiling the game.

**Comment by Mashrien** [comment] 2015-07-05 21:01
pardis, if you looked at the original topic on Unturned, I said it was an Unturned bug.

Don't hound the shit out of rocket without reading yo.

**Comment by kaegann** [comment] 2015-07-05 21:04
Memory leak caused by rocket. Not unturned. I can host a vanilla server for hours with not one single issue. Install rocket and 10 minutes later it crashes. Stop acting all high and mighty and bashing your users when they tell you your wrong. Biggest disgrace for a coding team I have ever seen.

**Comment by Mashrien** [comment] 2015-07-05 21:08
@kaegann To you "it's not vanilla", but I've replicated the bug in unturned itself (though it doesn't LOOK like it) If you join a vanilla server, it claims ~400kb of memory, when that user leaves the server, it only releases ~200kb of memory.  Rocket may exacerbate the bug, making it more noticable, but it IS in fact an Unturned bug.

Further proof of this: ZERO CODE CHANGED in Rocket for 3.11.1.0 when there was no leak, to 3.11.2.0 when the leak began.

So before you rant at people that've been in the IT and programming industries for well over a decade, research your shit, otherwise you just make yourself look like an imbecile.

Also, Sven banned you from the repo for being a stupid dick. :dancers:

**Comment by kaegann** [comment] 2015-07-05 21:10
Lol real mature. Throwing around swear words and telling me to cry somewhere else, then edit your message to act like a 5 year old and say I'm blocked. You're a disgrace to the IT community freak. Get over yourselves lol

**Comment by fr34kyn01535** [comment] 2015-07-26 14:27
Seems to be fixed in latest version of Unturned,.. was indeed a Unturned issue..

**Closed by fr34kyn01535** 2015-07-26 14:27 UTC
Labels: unturned bug
